name: Build and Publish Docker

on:
        push:
                branches:
                        - 19.6.0
        workflow_dispatch:

jobs:
        build_and_push:
                runs-on: ubuntu-latest
                env:
                        IMAGE_NAME: alpine-node19
                steps:
                        - name: checkout
                          uses: actions/checkout@v3

                        - name: Set up Docker Buildx
                          uses: docker/setup-buildx-action@v2

                        - name: Login to Github Container Registry
                          uses: docker/login-action@v2
                          with:
                                  registry: ghcr.io
                                  username: ${{ github.repository_owner }}
                                  password: ${{ secrets.GITHUB_TOKEN }}

                        - name: Build and push
                          uses: docker/build-push-action@v3
                          with:
                                  context: .
                                  push: true
                                  tags: |
                                          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:19.6.0
